#!/bin/bash
set -e
set -u
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup


# Directory to backup.
# This directory will be created by setup_data "$@"().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data "$@"

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out /dev/null
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
@#
@# full to Pool1
@#
run job=$JobName pool=Pool1  level=Full yes
status director
status client
status storage=File
wait
messages
@#
@# full to Pool2
@#
run job=$JobName pool=Pool2  level=Full yes
status director
status client
status storage=File
wait
messages

@#
@# full to Pool1
@#
run job=$JobName pool=Pool1  level=Full yes
status director
status client
status storage=File
wait
messages
@#
@# full to Pool2
@#

run job=$JobName pool=Pool2  level=Full yes
status director
status client
status storage=File
wait
messages
wait
messages
quit
END_OF_DATA

run_bareos "$@"
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_diff ${BackupDirectory}
end_test
